# Docker Compose for Apple MCP Email Task Manager

services:
  postgres:
    image: postgres:15-alpine
    container_name: email_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-email_management}
      POSTGRES_USER: ${DB_USER:-email_admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secure_password_2024}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U email_admin -d email_management"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - email_network

  redis:
    image: redis:7-alpine
    container_name: email_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - email_network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  email_network:
    driver: bridge
