declare const styles: {
  readonly dateRangePicker: string;
  readonly dateRangeInput: string;
  readonly disabled: string;
  readonly calendarIcon: string;
  readonly dateRangeText: string;
  readonly clearButton: string;
  readonly dateRangeDropdown: string;
  readonly dateRangeContent: string;
  readonly calendarSection: string;
  readonly calendarHeader: string;
  readonly navButton: string;
  readonly monthYear: string;
  readonly weekdayHeaders: string;
  readonly weekdayHeader: string;
  readonly calendarGrid: string;
  readonly calendarCell: string;
  readonly otherMonth: string;
  readonly selectedStart: string;
  readonly selectedEnd: string;
  readonly inRange: string;
  readonly hovered: string;
  readonly presetsSection: string;
  readonly presetsHeader: string;
  readonly presetsList: string;
  readonly presetButton: string;
};
export default styles;